# COMMENT: This a rule for Single Page Applications as Docz site is one
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
command = "npm run build"
publish = "public/"

[[plugins]]
package = "@netlify/plugin-gatsby"
