# COMMENT: This a rule for Single Page Applications as Docz site is one
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
build:
  command: yarn build
  commandOrigin: ui
  publish: /opt/build/repo
  publishOrigin: ui
  functions:
  '*': {}
  redirectsOrigin: config
